USE [master]
GO

/****** Object:  Table [dbo].[GAME_TURNS]    Script Date: 12/5/2024 4:57:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GAME_TURNS](
	[GAME_ID] [int] NOT NULL,
	[PLAYER_ID] [int] NULL,
	[TURN_ORDER] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[GAME_ID] ASC,
	[TURN_ORDER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


