USE [master]
GO

/****** Object:  Table [dbo].[PLAYERSESSIONS]    Script Date: 12/5/2024 4:57:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PLAYERSESSIONS](
	[SESSIONID] [uniqueidentifier] NOT NULL,
	[PLAYERID] [int] NOT NULL,
	[EXPIRATION] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SESSIONID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PLAYERSESSIONS]  WITH CHECK ADD FOREIGN KEY([PLAYERID])
REFERENCES [dbo].[player] ([PLAYERID])
GO


