USE [master]
GO

/****** Object:  Table [dbo].[tile]    Script Date: 12/5/2024 4:57:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tile](
	[TILE_ID] [uniqueidentifier] NOT NULL,
	[PLAYER_CONTROL_ID] [int] NULL,
	[OCCUPIED] [uniqueidentifier] NULL,
	[TILE_TYPE] [int] NULL,
	[is_CITY] [bit] NULL,
	[CITY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[TILE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


