USE master
CREATE TABLE games(
	GAME_ID INT IDENTITY(1,1),
	MAP_ID INT,
	PLAYERCOUNT INT,
	GAMETYPE INT,
	PRIMARY KEY (GAME_ID)
	)
CREATE TABLE player(
	PLAYER_ID INT IDENTITY(1,1),
	ACTIVE_GAME INT,
	PRIMARY KEY(PLAYER_ID)
	)
CREATE TABLE map(
	MAP_ID INT IDENTITY(1,1),
	TILE_ID INT,
	X INT,
	Y INT,
	PRIMARY KEY(MAP_ID))
CREATE TABLE tile(
	TILE_ID INT IDENTITY(1,1),
	TILE_RESOURCE_ID INT,
	PLAYER_CONTROL_ID INT,
	OCCUPIED INT,
	TILE_TYPE INT
	PRIMARY KEY(TILE_ID)
	)
CREATE TABLE tile_type(
	TILE_TYPE_ID INT IDENTITY(1,1),
	TILE_NAME VARCHAR(50),
	TILE_DIFF INT,
	WOOD_PER_TURN INT,
	FOOD_PER_TURN INT,
	STONE_PER_TURN INT,
	IRON_PER_TURN INT,
	is_CITY BIT,
	CITY_ID INT
	PRIMARY KEY(TILE_TYPE_ID)
)
CREATE TABLE city(
	CITY_ID INT IDENTITY(1,1),
	TILE_ID INT,
	CITY_NAME VARCHAR(50),
	PRODUCTION_PER_TURN INT,
	SCIENCE_PER_TURN INT,
	CITY_POP INT,
	CURRENT_BUILD INT
)
CREATE TABLE building(
	BUILDING_ID INT IDENTITY(1,1),
	BUILDING_NAME VARCHAR(50),
	CITY_ID INT,
	MODIFIER_TYPE BIT,
	MODIFIER VARCHAR(10),
	MODIFIER_AMOUNT INT,
	WOOD_COST INT,
	IRON_COST INT,
	STONE_COST INT,
	PRODUCTION_COST INT
	)
CREATE TABLE active_building(
	BUILDING_ID INT,
	CITY_ID INT,
	)
